// <auto-generated />
using System;
using KintelaData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KintelaData.Migrations
{
    [DbContext(typeof(KintelaContext))]
    [Migration("20240330125905_AddRecetas")]
    partial class AddRecetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoriaReceta", b =>
                {
                    b.Property<int>("CategoriasCategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("RecetasRecetaId")
                        .HasColumnType("int");

                    b.HasKey("CategoriasCategoriaId", "RecetasRecetaId");

                    b.HasIndex("RecetasRecetaId");

                    b.ToTable("CategoriaReceta");
                });

            modelBuilder.Entity("KintelaDomain.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nombre = "Carne"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nombre = "Ensalada"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nombre = "Huevos"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Nombre = "Legumbres"
                        },
                        new
                        {
                            CategoriaId = 5,
                            Nombre = "Pasta"
                        },
                        new
                        {
                            CategoriaId = 6,
                            Nombre = "Patatas"
                        },
                        new
                        {
                            CategoriaId = 7,
                            Nombre = "Pescado"
                        },
                        new
                        {
                            CategoriaId = 8,
                            Nombre = "Postre"
                        },
                        new
                        {
                            CategoriaId = 9,
                            Nombre = "Sandwich"
                        },
                        new
                        {
                            CategoriaId = 10,
                            Nombre = "Sopa"
                        },
                        new
                        {
                            CategoriaId = 11,
                            Nombre = "Tortilla"
                        },
                        new
                        {
                            CategoriaId = 12,
                            Nombre = "Verdura"
                        });
                });

            modelBuilder.Entity("KintelaDomain.Disco", b =>
                {
                    b.Property<int>("DiscoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscoId"));

                    b.Property<string>("Caratula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discografica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Productor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublicacion")
                        .HasColumnType("int");

                    b.HasKey("DiscoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("Discos");

                    b.HasData(
                        new
                        {
                            DiscoId = 1,
                            Caratula = "1.jpg",
                            Discografica = "Shelter Records",
                            GrupoId = 3,
                            Nombre = "Tom Petty & The Heartbreakers",
                            Productor = "Denny Cordell",
                            YearPublicacion = 1976
                        },
                        new
                        {
                            DiscoId = 2,
                            Caratula = "2.jpg",
                            Discografica = "Shelter Records",
                            GrupoId = 3,
                            Nombre = "You're Gonna Get It!",
                            Productor = "Denny Cordell, Noah Shark, Tom Petty",
                            YearPublicacion = 1978
                        },
                        new
                        {
                            DiscoId = 3,
                            Caratula = "3.jpg",
                            Discografica = "Backstreet Records",
                            GrupoId = 3,
                            Nombre = "Damn the Torpedoes",
                            Productor = "Jimmy Iovine, Tom Petty",
                            YearPublicacion = 1979
                        },
                        new
                        {
                            DiscoId = 4,
                            Caratula = "4.jpg",
                            Discografica = "Backstreet Records",
                            GrupoId = 3,
                            Nombre = "Hard Promises",
                            Productor = "Jimmy Iovine, Tom Petty",
                            YearPublicacion = 1981
                        },
                        new
                        {
                            DiscoId = 5,
                            Caratula = "5.jpg",
                            Discografica = "Backstreet Records",
                            GrupoId = 3,
                            Nombre = "Long After Dark",
                            Productor = "Jimmy Iovine, Tom Petty",
                            YearPublicacion = 1982
                        },
                        new
                        {
                            DiscoId = 6,
                            Caratula = "6.jpg",
                            Discografica = "MCA Records",
                            GrupoId = 3,
                            Nombre = "Southern Accents",
                            Productor = "Tom Petty, Dave Stewart, Jimmy Iovine, Robbie Robertson, Mike Campbell",
                            YearPublicacion = 1985
                        },
                        new
                        {
                            DiscoId = 7,
                            Caratula = "7.jpg",
                            Discografica = "MCA Records",
                            GrupoId = 3,
                            Nombre = "Let Me Up (I've Had Enough)",
                            Productor = "Tom Petty, Mike Campbell",
                            YearPublicacion = 1987
                        },
                        new
                        {
                            DiscoId = 8,
                            Caratula = "8.jpg",
                            Discografica = "MCA Records",
                            GrupoId = 3,
                            Nombre = "Into the Great Wide Open",
                            Productor = "Jeff Lynne, Tom Petty, Mike Campbell",
                            YearPublicacion = 1991
                        },
                        new
                        {
                            DiscoId = 9,
                            Caratula = "9.jpg",
                            Discografica = "Warner Bros. Records",
                            GrupoId = 3,
                            Nombre = "Songs and Music from 'She's the One'",
                            Productor = "Rick Rubin, Tom Petty, Mike Campbell",
                            YearPublicacion = 1996
                        },
                        new
                        {
                            DiscoId = 10,
                            Caratula = "10.jpg",
                            Discografica = "Warner Bros. Records",
                            GrupoId = 3,
                            Nombre = "Echo",
                            Productor = "Rick Rubin, Tom Petty, Mike Campbell",
                            YearPublicacion = 1999
                        },
                        new
                        {
                            DiscoId = 11,
                            Caratula = "11.jpg",
                            Discografica = "Warner Bros. Records",
                            GrupoId = 3,
                            Nombre = "The Last DJ",
                            Productor = "Tom Petty, Mike Campbell, George Drakoulias",
                            YearPublicacion = 2002
                        },
                        new
                        {
                            DiscoId = 12,
                            Caratula = "12.jpg",
                            Discografica = "Reprise Records",
                            GrupoId = 3,
                            Nombre = "Mojo",
                            Productor = "Tom Petty, Mike Campbell, Ryan Ulyate",
                            YearPublicacion = 2010
                        },
                        new
                        {
                            DiscoId = 13,
                            Caratula = "13.jpg",
                            Discografica = "Reprise Records",
                            GrupoId = 3,
                            Nombre = "Hypnotic Eye",
                            Productor = "Tom Petty, Mike Campbell, Ryan Ulyate",
                            YearPublicacion = 2014
                        },
                        new
                        {
                            DiscoId = 14,
                            Caratula = "14.jpg",
                            Discografica = "Warner Bros. Records",
                            GrupoId = 4,
                            Nombre = "Wildflowers",
                            Productor = "Rick Rubin, Tom Petty, Mike Campbell",
                            YearPublicacion = 1994
                        },
                        new
                        {
                            DiscoId = 15,
                            Caratula = "15.jpg",
                            Discografica = "American Recordings",
                            GrupoId = 4,
                            Nombre = "Highway Companion",
                            Productor = "Jeff Lynne, Tom Petty, Mike Campbell",
                            YearPublicacion = 2006
                        },
                        new
                        {
                            DiscoId = 16,
                            Caratula = "16.jpg",
                            Discografica = "Warner Bros. Records",
                            GrupoId = 5,
                            Nombre = "Traveling Wilburys Vol. 1",
                            Productor = "Jeff Lynne, George Harrison",
                            YearPublicacion = 1998
                        },
                        new
                        {
                            DiscoId = 17,
                            Caratula = "17.jpg",
                            Discografica = "Warner Bros. Records",
                            GrupoId = 5,
                            Nombre = "Traveling Wilburys Vol. 3",
                            Productor = "Jeff Lynne, George Harrison",
                            YearPublicacion = 1998
                        },
                        new
                        {
                            DiscoId = 18,
                            Caratula = "1.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Please Please Me",
                            Productor = "George Martin",
                            YearPublicacion = 1963
                        },
                        new
                        {
                            DiscoId = 19,
                            Caratula = "1.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "With The Beatles",
                            Productor = "George Martin",
                            YearPublicacion = 1963
                        },
                        new
                        {
                            DiscoId = 20,
                            Caratula = "2.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "A Hard Day's Night",
                            Productor = "George Martin",
                            YearPublicacion = 1964
                        },
                        new
                        {
                            DiscoId = 21,
                            Caratula = "3.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Beatles for Sale",
                            Productor = "George Martin",
                            YearPublicacion = 1964
                        },
                        new
                        {
                            DiscoId = 22,
                            Caratula = "4.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Help!",
                            Productor = "George Martin",
                            YearPublicacion = 1965
                        },
                        new
                        {
                            DiscoId = 23,
                            Caratula = "5.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Rubber Soul",
                            Productor = "George Martin",
                            YearPublicacion = 1965
                        },
                        new
                        {
                            DiscoId = 24,
                            Caratula = "6.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Revolver",
                            Productor = "George Martin",
                            YearPublicacion = 1966
                        },
                        new
                        {
                            DiscoId = 25,
                            Caratula = "7.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Sgt. Pepper's Lonely Hearts Club Band",
                            Productor = "George Martin",
                            YearPublicacion = 1967
                        },
                        new
                        {
                            DiscoId = 26,
                            Caratula = "8.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Magical Mystery Tour",
                            Productor = "George Martin",
                            YearPublicacion = 1967
                        },
                        new
                        {
                            DiscoId = 27,
                            Caratula = "9.png",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "The Beatles (White Album)",
                            Productor = "George Martin",
                            YearPublicacion = 1968
                        },
                        new
                        {
                            DiscoId = 28,
                            Caratula = "10.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Yellow Submarine",
                            Productor = "George Martin",
                            YearPublicacion = 1969
                        },
                        new
                        {
                            DiscoId = 29,
                            Caratula = "11.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Abbey Road",
                            Productor = "George Martin",
                            YearPublicacion = 1969
                        },
                        new
                        {
                            DiscoId = 30,
                            Caratula = "12.jpeg",
                            Discografica = "Parlophone",
                            GrupoId = 1,
                            Nombre = "Let It Be",
                            Productor = "George Martin",
                            YearPublicacion = 1970
                        },
                        new
                        {
                            DiscoId = 31,
                            Caratula = "31.jpeg",
                            Discografica = "Decca Records",
                            GrupoId = 2,
                            Nombre = "The Rolling Stones",
                            Productor = "Andrew Loog Oldham",
                            YearPublicacion = 1964
                        },
                        new
                        {
                            DiscoId = 32,
                            Caratula = "32.jpeg",
                            Discografica = "Decca Records",
                            GrupoId = 2,
                            Nombre = "The Rolling Stones No. 2",
                            Productor = "Andrew Loog Oldham",
                            YearPublicacion = 1965
                        },
                        new
                        {
                            DiscoId = 33,
                            Caratula = "33.jpeg",
                            Discografica = "Decca Records",
                            GrupoId = 2,
                            Nombre = "Out of Our Heads",
                            Productor = "Andrew Loog Oldham",
                            YearPublicacion = 1965
                        },
                        new
                        {
                            DiscoId = 34,
                            Caratula = "34.jpeg",
                            Discografica = "Decca Records",
                            GrupoId = 2,
                            Nombre = "Aftermath",
                            Productor = "Andrew Loog Oldham",
                            YearPublicacion = 1966
                        },
                        new
                        {
                            DiscoId = 35,
                            Caratula = "35.jpeg",
                            Discografica = "Decca Records",
                            GrupoId = 2,
                            Nombre = "Between the Buttons",
                            Productor = "Andrew Loog Oldham",
                            YearPublicacion = 1967
                        },
                        new
                        {
                            DiscoId = 36,
                            Caratula = "36.jpeg",
                            Discografica = "Decca Records",
                            GrupoId = 2,
                            Nombre = "Their Satanic Majesties Request",
                            Productor = "The Rolling Stones",
                            YearPublicacion = 1967
                        },
                        new
                        {
                            DiscoId = 37,
                            Caratula = "37.jpeg",
                            Discografica = "Decca Records",
                            GrupoId = 2,
                            Nombre = "Beggar's Banquet",
                            Productor = "Jimmy Miller",
                            YearPublicacion = 1968
                        },
                        new
                        {
                            DiscoId = 38,
                            Caratula = "38.jpeg",
                            Discografica = "Decca Records",
                            GrupoId = 2,
                            Nombre = "Let It Bleed",
                            Productor = "Jimmy Miller",
                            YearPublicacion = 1969
                        },
                        new
                        {
                            DiscoId = 39,
                            Caratula = "39.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Sticky Fingers",
                            Productor = "Jimmy Miller",
                            YearPublicacion = 1971
                        },
                        new
                        {
                            DiscoId = 40,
                            Caratula = "40.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Exile on Main St",
                            Productor = "Jimmy Miller",
                            YearPublicacion = 1972
                        },
                        new
                        {
                            DiscoId = 41,
                            Caratula = "41.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Goats Head Soup",
                            Productor = "Jimmy Miller",
                            YearPublicacion = 1973
                        },
                        new
                        {
                            DiscoId = 42,
                            Caratula = "42.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "It's Only Rock 'n Roll",
                            Productor = "The Glimmer Twins",
                            YearPublicacion = 1974
                        },
                        new
                        {
                            DiscoId = 43,
                            Caratula = "43.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Black and Blue",
                            Productor = "The Glimmer Twins",
                            YearPublicacion = 1976
                        },
                        new
                        {
                            DiscoId = 44,
                            Caratula = "43.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Some Girls",
                            Productor = "The Glimmer Twins",
                            YearPublicacion = 1978
                        },
                        new
                        {
                            DiscoId = 45,
                            Caratula = "44.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Emotional Rescue",
                            Productor = "The Glimmer Twins",
                            YearPublicacion = 1980
                        },
                        new
                        {
                            DiscoId = 46,
                            Caratula = "45.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Tatoo You",
                            Productor = "The Glimmer Twins",
                            YearPublicacion = 1981
                        },
                        new
                        {
                            DiscoId = 47,
                            Caratula = "46.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Undercover",
                            Productor = "The Glimmer Twins, Chris Kimsey",
                            YearPublicacion = 1983
                        },
                        new
                        {
                            DiscoId = 48,
                            Caratula = "47.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Dirty Work",
                            Productor = "The Glimmer Twins, Steve Lilywhite",
                            YearPublicacion = 1986
                        },
                        new
                        {
                            DiscoId = 49,
                            Caratula = "48.jpeg",
                            Discografica = "Rolling Stones Records",
                            GrupoId = 2,
                            Nombre = "Steel Wheels",
                            Productor = "The Glimmer Twins, Chris Kimsey",
                            YearPublicacion = 1989
                        },
                        new
                        {
                            DiscoId = 50,
                            Caratula = "49.jpeg",
                            Discografica = "Virgin Records",
                            GrupoId = 2,
                            Nombre = "Voodoo Lounge",
                            Productor = "The Glimmer Twins, Don Was",
                            YearPublicacion = 1994
                        },
                        new
                        {
                            DiscoId = 51,
                            Caratula = "50.jpeg",
                            Discografica = "Virgin Records",
                            GrupoId = 2,
                            Nombre = "Bridge to Babylon",
                            Productor = "The Glimmer Twins. Don Was, Rob Fraboni, Danny Saber, Pierre de Beauport. The Dust Brothers",
                            YearPublicacion = 1997
                        },
                        new
                        {
                            DiscoId = 52,
                            Caratula = "51.jpeg",
                            Discografica = "Virgin Records",
                            GrupoId = 2,
                            Nombre = "A Bigger Bang",
                            Productor = "The Glimmer Twins, Don Was, Matt Clifford",
                            YearPublicacion = 2005
                        },
                        new
                        {
                            DiscoId = 53,
                            Caratula = "52.jpeg",
                            Discografica = "Polydor Records",
                            GrupoId = 2,
                            Nombre = "Blue & Lonesome",
                            Productor = "The Glimmer Twins, Don Was",
                            YearPublicacion = 2016
                        },
                        new
                        {
                            DiscoId = 54,
                            Caratula = "53.jpeg",
                            Discografica = "Geffen Records",
                            GrupoId = 2,
                            Nombre = "Hackney Diamonds",
                            Productor = "Andrew Watt",
                            YearPublicacion = 2023
                        });
                });

            modelBuilder.Entity("KintelaDomain.Grupo", b =>
                {
                    b.Property<int>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrupoId");

                    b.ToTable("Grupos");

                    b.HasData(
                        new
                        {
                            GrupoId = 1,
                            Nombre = "The Beatles"
                        },
                        new
                        {
                            GrupoId = 2,
                            Nombre = "The Rolling Stones"
                        },
                        new
                        {
                            GrupoId = 3,
                            Nombre = "Tom Petty & The Heart Breakers"
                        },
                        new
                        {
                            GrupoId = 4,
                            Nombre = "Tom Petty"
                        },
                        new
                        {
                            GrupoId = 5,
                            Nombre = "Traveling Wilburys"
                        });
                });

            modelBuilder.Entity("KintelaDomain.MenuSemanal", b =>
                {
                    b.Property<int>("MenuSemanalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuSemanalId"));

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int?>("RecetaPostreDomingo")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPostreJueves")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPostreLunes")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPostreMartes")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPostreMiercoles")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPostreSabado")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPostreViernes")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPrimerPlatoDomingo")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPrimerPlatoJueves")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPrimerPlatoLunes")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPrimerPlatoMartes")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPrimerPlatoMiercoles")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPrimerPlatoSabado")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaPrimerPlatoViernes")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaSegundoPlatoDomingo")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaSegundoPlatoJueves")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaSegundoPlatoLunes")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaSegundoPlatoMartes")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaSegundoPlatoMiercoles")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaSegundoPlatoSabado")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaSegundoPlatoViernes")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MenuSemanalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MenuSemanal");
                });

            modelBuilder.Entity("KintelaDomain.Receta", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetaId"));

                    b.Property<int?>("Comensales")
                        .HasColumnType("int");

                    b.Property<string>("EnlaceVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredientes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preparacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Presentacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecetaId");

                    b.ToTable("Recetas");

                    b.HasData(
                        new
                        {
                            RecetaId = 1,
                            EnlaceVideo = "https://www.hogarmania.com/cocina/recetas/pescados-mariscos/langostinos-horno-perejil-karlos-arguinano.html?utm_source=TwitterKarlos&utm_medium=social&utm_campaign=langostinos-horno-perejil-karlos-arguinano",
                            Imagen = "1.jpg",
                            Ingredientes = "[\"24 langostinos\",\"1 lim\\u00F3n\",\"40 ml de whisky\",\"sal\",\"2 dientes de ajo\",\"1/2 guindilla\",\"aceite de oliva virgen extra\",\"perejil\"]",
                            Nombre = "Langostinos al horno",
                            Preparacion = "[\"Para hacer esta original versi\\u00F3n de la salsa de ajo y perejil, pela y pica los dientes de ajo en daditos, y ponlos en un bol. Pica tambi\\u00E9n la guindilla y un manojo de perejil (necesitamos una cucharada de perejil) y agr\\u00E9galos. Vierte el whisky y 60 ml de aceite, y mezcla bien\",\"Pela los langostinos dej\\u00E1ndoles la cabeza y la punta de la cola, sin pelar. Col\\u00F3calos en una bandeja de horno, sazona y ader\\u00E9zalos con la mezcla de aceite, whisky, ajo, guindilla y perejil.\",\"Hornea los langostinos (con el horno precalentado) a 220\\u00BAC durante 4-5 minutos\"]",
                            Presentacion = "[\"Sirve 6 langostinos en cada plato y ri\\u00E9galos con el l\\u00EDquido de la bandeja del horno.\",\"Lava el lim\\u00F3n, c\\u00F3rtalo en 4 y coloca un trozo en cada plato. Dec\\u00F3ralos con unas hojas de perejil fresco\"]"
                        },
                        new
                        {
                            RecetaId = 2,
                            Imagen = "16.jpg",
                            Nombre = "Tortilla de Patatas"
                        },
                        new
                        {
                            RecetaId = 3,
                            Nombre = "Garbanzos con chorizo y Zanquarrón"
                        },
                        new
                        {
                            RecetaId = 4,
                            Ingredientes = "[\"1 cola de merluza grandecita\",\"500 gr de cebolla\",\"2 patatas cocidas\",\"75 gr de aceite de oliva virgen extra\",\"5 gr de piment\\u00F3n\",\"50 gr de aceite de oliva (refrito): aceite donde has dorado unos ajos\",\"20 gr de vinagre de sidra\",\"1 cayena\",\"16 gr de ajo laminado\",\"perejil picado\",\"una pizca de sal\"]",
                            Nombre = "Merluza al Horno",
                            Preparacion = "[\"Precalentar el horno a 180\\u00BA\",\"Se corta la cebolla en juliana y se frie en una sart\\u00E9n con los 75 gr de aceite de oliva durante unos 30 o 40 minutos hasta que est\\u00E9 muy pochada\",\"Se agrega el piment\\u00F3n de la vera en la sart\\u00E9n, se mueve bien el conjunto y cuando est\\u00E9 ligado se extiende sobre una placa del horno\",\"Se colocan encima las patatas cocidas cortadas en rodajas de medio centr\\u00EDmetro de grosor y se corona el conjunto con la cola de merluza, abierta en libro y perfectamente desespinada, con la piel hacia abajo en contacto con las patatas\",\"Se mete la placa en el horno y se cocina entorno a 8 minutos\"]",
                            Presentacion = "[\"Se ponen los 50 gr de aceite de oliva refrito en una sart\\u00E9n junto al ajo y la cayena\",\"Cuando los ajos empiecen a bailar y tomen color se vierte el conjunto sobre la merluza y las patatas que previamente habremos sacado del horno\",\"Se echa el vinagre sobre la misma sart\\u00E9n, se deja que de un hervor y se vierte de nuevo sobre la merluza\",\"Se escurre todo el jugo de la bandeja de hornear sobre la sart\\u00E9n y se lleva a ebullici\\u00F3n.\",\"Se vierte de nuevo sobre la merluza y se repite este paso 3 veces en total\",\"Se espolvorea con perejil y se sirve inmediatamente\"]"
                        },
                        new
                        {
                            RecetaId = 5,
                            Imagen = "5.jpg",
                            Nombre = "Brócoli con gulas"
                        },
                        new
                        {
                            RecetaId = 6,
                            Nombre = "Pechugas a la plancha"
                        },
                        new
                        {
                            RecetaId = 7,
                            Comensales = 4,
                            EnlaceVideo = "https://www.hogarmania.com/cocina/recetas/ensaladas-verduras/patatas-riojana-3737.html",
                            Imagen = "2.jpg",
                            Ingredientes = "[\"3 chorizos\",\"1 pimiento verde\",\"1 cabeza de ajos\",\"aceite de oliva\",\"2 hojas de laurel\",\"perejil (para decorar)\",\"6 patatas\",\"1 cebolla\",\"2 pimientos choriceros\",\"agua\",\"sal\",\"1 guindilla\"]",
                            Nombre = "Patatas a la riojana",
                            Preparacion = "[\"Pica la cebolla y el pimiento verde y ponlos en una olla r\\u00E1pida con un chorrito de aceite.\",\"A\\u00F1ade la cabeza de ajos, las hojas de laurel y la guindilla (sin pepitas). Incorpora los chorizos cortados en rodajas y las patatas peladas y cascadas. Cubre con agua y sazona. Cierra la olla y cocina al 1 durante 5 minutos a partir de que empiece a salir el vapor.\",\"Si no utilizas una olla r\\u00E1pida, cocina hasta que las patatas est\\u00E9n guisadas (30-40 minutos aproximadamente).\",\"Retira las semillas a los pimientos choriceros y ponlos a remojo en un cazo con agua templada. Cuando se ablanden, deja templar, retira la carne con un cuchillo y p\\u00EDcala.\",\"Destapa la olla, saca la cabeza de ajos y la guindilla y desgrasa con un cuchar\\u00F3n. A\\u00F1ade los pimientos choriceros, remueve y cocina durante dos minutos m\\u00E1s (para que se mezclen los sabores).\",\"Pon a punto de sal.\"]",
                            Presentacion = "[\"Sirve las patatas a la riojana en un plato hondo y decora con una hojita de perejil.\"]"
                        },
                        new
                        {
                            RecetaId = 8,
                            Imagen = "7.jpg",
                            Nombre = "Ensalada de pasta"
                        },
                        new
                        {
                            RecetaId = 9,
                            Imagen = "11.jpg",
                            Nombre = "Sandwich de Jamon York y Queso"
                        },
                        new
                        {
                            RecetaId = 10,
                            Imagen = "10.jpg",
                            Ingredientes = "[\"1 patata\",\"1 pimiento rojo\",\"1 pimiento verde\",\"1 tomate\",\"1 zanahoria\",\"1 cebolla\",\"2 ajos\",\"1 cucharada de piment\\u00F3n dulce\",\"1 cucharadita de pimienta negra\"]",
                            Nombre = "Alubias Blancas de Bote",
                            Preparacion = "[\"Pochas la cebolla en una cazuela\",\"Una vez pochada a\\u00F1ades los pimientos y los ajos bien picaditos\",\"Cuando veamos que los pimientos y la cebolla est\\u00E1n bien integrados a\\u00F1adimos el tomate tambi\\u00E9n picadito y sofreimos un poco mas\",\"A continuaci\\u00F3n a\\u00F1adimos la zanahoria a rodajas, la patata a gajos peque\\u00F1os, cubrimos con agua, ponemos la sal, pimienta y el pimenton dulce\",\"Cuando ya est\\u00E9n la patata y la zanahoria blandas y el agua haya reducido un poco a\\u00F1adimos las alubias bien lavadas, movemos con vuidado que no se rompan y listo\"]"
                        },
                        new
                        {
                            RecetaId = 11,
                            Imagen = "6.jpg",
                            Ingredientes = "[\"carne picada\",\"pimiento rojo\",\"pimiento verde\",\"cebolla\",\"tomate frito\",\"maiz\",\"tortillas de trigo\",\"sal\",\"Tabasco\",\"Salsa Barbacoa\",\"Ketchp\",\"queso rallado\"]",
                            Nombre = "Burritos de carne picada",
                            Preparacion = "[\"Pochamos la cebolla y los pimientos\",\"Cuando est\\u00E9n pochados a\\u00F1adimos la carne picada y la sal\",\"Cuando la carne est\\u00E9 hecha a\\u00F1adimos el maiz y el tomate frito\"]",
                            Presentacion = "[\"Puedes acompa\\u00F1ar con unos nachos y guacamole\"]"
                        },
                        new
                        {
                            RecetaId = 12,
                            Imagen = "8.jpg",
                            Ingredientes = "[\"vainas\",\"carne de ternera\",\"cebolla\",\"pimiento verde\",\"sal\"]",
                            Nombre = "Sandwich de Jamon York y Queso"
                        },
                        new
                        {
                            RecetaId = 13,
                            Ingredientes = "[\"Medio vaso de lentejas por cada raci\\u00F3n\",\"un pu\\u00F1ado de arroz\",\"media cebolla\",\"2 o 3 zanahorias\",\"2 o 3 puerros\",\"1 pimiento verde\",\"2 o 3 patatas\",\"2 tomates\",\"chorizo de cocido\",\"costilla de cerdo\",\"sal\",\"aceite de oliva\"]",
                            Nombre = "Lentejas con arroz",
                            Preparacion = "[\"Pones a hervir los tomates para pelarlos y trocearlos antes de echarlos a la olla\",\"Echas las lentejas y el arroz en la olla con un vaso de agua por cada raci\\u00F3n\",\"Troceas finita la cebolla y la echas tb en la olla\",\"Troceas las zanahorias peladas y a la olla\",\"Troceas las patatas y los puerros y a la olla\",\"Echas el pimiento verde troceado solo en 2 para darle sabor, luego lo quitas\",\"Echas los tomates troceados\",\"Echas el chorizo y la costilla\",\"Si echas costilla mas de 15 minutos de olla\",\"Echas un chorro de aceite y sal\",\"Pones la olla 15 minutos\"]"
                        },
                        new
                        {
                            RecetaId = 14,
                            Imagen = "4.jpg",
                            Ingredientes = "[\"anchoas\",\"harina\",\"huevo\",\"aceite de oliva\",\"cogollos de lechuga\"]",
                            Nombre = "Anchoas albardadas",
                            Preparacion = "[\"Se limpian las anchoas quit\\u00E1ndoles la cabeza y las tripas\",\"Se pasan por harina y huevo\",\"Se fr\\u00EDen en aceite de oliva\"]",
                            Presentacion = "[\"Se sirven con cogollos de lechuga\"]"
                        },
                        new
                        {
                            RecetaId = 15,
                            EnlaceVideo = "https://www.youtube.com/watch?v=myTmIYDStWs",
                            Ingredientes = "[\"1 rodaballo\",\"3 patatas\",\"1 pimiento verde italiano\",\"2 chalotas\",\"2 tomates rama\",\"2 dientes de ajo\",\"Perejil\",\"100 ml de vino blanco para el majado\",\"150 ml de vino blanco para las patatas\",\"Sal\",\"Aceite de oliva virgen extra\"]",
                            Nombre = "Robadallo al horno"
                        },
                        new
                        {
                            RecetaId = 16,
                            Nombre = "Alubias"
                        },
                        new
                        {
                            RecetaId = 17,
                            Nombre = "Lubina al horno"
                        },
                        new
                        {
                            RecetaId = 18,
                            Nombre = "Tarta Lotus"
                        },
                        new
                        {
                            RecetaId = 19,
                            Nombre = "Cordero al horno"
                        },
                        new
                        {
                            RecetaId = 20,
                            Nombre = "Hamburgesas veganas"
                        },
                        new
                        {
                            RecetaId = 21,
                            Nombre = "Fajitas de pollo"
                        },
                        new
                        {
                            RecetaId = 22,
                            Nombre = "Berenjena rellena al horno"
                        },
                        new
                        {
                            RecetaId = 23,
                            Nombre = "Coliflor gratinada"
                        },
                        new
                        {
                            RecetaId = 24,
                            Nombre = "Pasta fresca con salsa de naranja"
                        },
                        new
                        {
                            RecetaId = 25,
                            Nombre = "Pulpo a feira"
                        },
                        new
                        {
                            RecetaId = 26,
                            Nombre = "Pasta con verduras"
                        },
                        new
                        {
                            RecetaId = 27,
                            Ingredientes = "[\"pasta a poder ser La Molisana Mezzi Rigatini N\\u00BA 32 integral\",\"carne picada\",\"cebolla\",\"zanahoria\",\"pimiento verde\",\"tomate frito\",\"sal\"]",
                            Nombre = "Pasta con carne picada",
                            Preparacion = "[\"Picas finoa la cebolla, la zanahoria y el pimiento\",\"Pochamos todo a\\u00F1adiendo sal\",\"Cuando est\\u00E9 todo pochado a\\u00F1adimos la carne picada a la que previamente hemos echado tambien sal\",\"Cuando la carne est\\u00E9 hecha desengrasas y a\\u00F1ades tomate frito\",\"Al final a\\u00F1ades la pasta cocida y mezclas todo bien\"]",
                            Presentacion = "[\"Puedes a\\u00F1adir queso rallado por encima\"]"
                        },
                        new
                        {
                            RecetaId = 28,
                            Nombre = "Guisantes con jamón"
                        },
                        new
                        {
                            RecetaId = 29,
                            Nombre = "Alcachofas con jamón"
                        },
                        new
                        {
                            RecetaId = 30,
                            Imagen = "14.jpg",
                            Ingredientes = "[\"carne picada\",\"3 huevos\",\"pan rallado\",\"2 zanahorias\",\"sal\",\"pimienta\",\"2 cebollas\",\"harina\",\"tomate frito\",\"2 rebanadas de pan bimbo\",\"leche\",\"1 pmiento verdea\"]",
                            Nombre = "Albóndigas en salsa",
                            Preparacion = "[\"Pones la carne picada en un bol\",\"Untamos en un poco de leche las 2 rebanadas de pan bimbo\",\"picas fina 1 cebolla y la pochas\",\"Echas esta cebolla pochada encima de la carne picada\",\"Echas las rebanadas de pan bimbo empapadas en leche en el bol\",\"Echas 3 huevos en el bol y mezclas todo con sal\",\"Para la salsa picas la otra cebolla, las zanahorias y el pimiento verde no hace falta que sea muy fino porque luego se bate todo\",\"Lo pochas todo y cuando est\\u00E9 pochado lo bates echando todo en un recipiente de batir y echando dentro tambi\\u00E9n tomate frito\",\"Haces las bolas enharinandolas y las fr\\u00EDes\",\"Cuando est\\u00E9n fritas las echas en una cazuela y echas la salsa por encima mas un poco de agua para que cubra y las tienes a fuego lento hasta que reduzca\"]"
                        },
                        new
                        {
                            RecetaId = 31,
                            Nombre = "Sopa de fideos"
                        },
                        new
                        {
                            RecetaId = 32,
                            Nombre = "Puré de calabaza"
                        },
                        new
                        {
                            RecetaId = 33,
                            Imagen = "12.jpg",
                            Ingredientes = "[\"bacalao\",\"patatas\",\"cebolla\",\"pimiento verde\",\"pimiento rojo\",\"aceite de oliva\",\"sal\"]",
                            Nombre = "Bacalao al Horno",
                            Preparacion = "[\"Precalientas el horno a 220 grados\",\"Echas un poco de aceite en la bandeja para que no se pege nada\",\"Cortas las patatas finas, les echas sal y las metes en el horno 15 minutos\",\"Cortas la cebolla en juliana y los pimientos, echas sal y los pones despu\\u00E9s otros 15 minutos en el horno\",\"Pones el bacalao en un hueco entre todo lo dem\\u00E1s, echas sal y lo metes 15 minutos mas a 200 grados\"]"
                        },
                        new
                        {
                            RecetaId = 34,
                            EnlaceVideo = "https://www.hogarmania.com/cocina/recetas/postres/tarta-fria-limon.html#google_vignette",
                            Imagen = "17.jpg",
                            Ingredientes = "[\"200 g de galletas\",\"100 g de mantequilla fundida\",\"2 huevos peque\\u00F1os\",\"50 g de mantequilla\",\"ralladura de 1/2 lim\\u00F3n\",\"4 g de hojas de gelatina\",\"100 g de az\\u00FAcar\",\"60 ml de zumo de lim\\u00F3n\",\"250 ml de nata (35% materia grasa)\"]",
                            Nombre = "Tarta de limón"
                        },
                        new
                        {
                            RecetaId = 35,
                            Imagen = "13.jpg",
                            Ingredientes = "[\"1 carcasa de pollo\",\"1 trozo cebolla\",\"1 puerro\",\"sal\",\"fideos\",\"1 huevo cocido\",\"1 zanahoria\"]",
                            Nombre = "Sopa de Pollo",
                            Preparacion = "[\"Pones la carcasa de pollo en una olla con agua junto con la cebolla, el puerro y las zanahorias\",\"Dejas hervir y echas sal\",\"Quitas todo\",\"A\\u00F1ades los fideos y dejas cocer el tiempo que te diga la bolsa delo que eches\"]",
                            Presentacion = "[\"Puedes a\\u00F1adir un huevo cocido picado por encima\",\"Puedes batir la zanahoria y el puerro que has sacado y echarlo encima\"]"
                        },
                        new
                        {
                            RecetaId = 36,
                            Nombre = "Entrecot a la plancha"
                        },
                        new
                        {
                            RecetaId = 37,
                            Ingredientes = "[\"lechuga\",\"maiz\",\"at\\u00FAn\",\"aceitunas\",\"huevo cocido\",\"aceite de oliva\",\"sal\",\"vinagre\",\"manzana\",\"mozzarella o burrata\",\"Pimiento picado\"]",
                            Nombre = "Ensalada Mixta"
                        },
                        new
                        {
                            RecetaId = 38,
                            Comensales = 4,
                            EnlaceVideo = "https://www.hogarmania.com/cocina/recetas/ensaladas-verduras/hamburguesas-calabaza.html",
                            Imagen = "15.jpg",
                            Ingredientes = "[\"1/2 kg de calabaza\",\"155 gr de copos de avena\",\"150 ml salsa de tomate\",\"aceite\",\"vinagre\",\"cebolla frita deshidratada\",\"1 zanahoria\",\"100 gr de queso mozzarella\",\"sal\",\"1/2 cucharadita de comino en polvo\",\"1 cucharada de ajo en polvo\"]",
                            Nombre = "Hamburguesas de Calabaza",
                            Preparacion = "[\"Calienta una cazuela con abundante agua. Pela la calabaza, troc\\u00E9ala y a\\u00F1\\u00E1dela a la cazuela. Sazona, tapa y cu\\u00E9cela durante 12-15 minutos\",\"Retira, esc\\u00FArrela, p\\u00E1sala a un bol y apl\\u00E1stala con un tenedor hasta dejarla reducida a un pur\\u00E9.\",\"Pela la zanahoria, r\\u00E1llala y res\\u00E9rvala\",\"Pon el pur\\u00E9 de calabaza, los copos de avena y la zanahoria rallada en un bol grande. Agrega una cucharada de perejil picado, la cebolla, el comino y el ajo. Sazona y mezcla bien\",\"Corta el queso en daditos\",\"Para montar las hamburguesas, pon un trozo de papel de horno (10 x 10 cm) sobre la tabla, coloca encima un aro de emplatar de 7 cm y rell\\u00E9nalo (a la mitad) con una parte de la mezcla, agrega unos daditos de queso y c\\u00FAbrelos con otra parte de la mezcla de calabaza. Presiona un poco la masa, pasa la hamburguesa a una fuente y retira el aro. Repite el proceso y monta otras 7 hamburguesas.\",\"Calienta un par de cucharadas de aceite en una plancha, a\\u00F1ade las hamburguesas (sin retirarles el papel) y coc\\u00EDnalas durante 3 minutos por cada lado.\"]",
                            Presentacion = "[\"Sirve en cada plato un par de hamburguesas y un poco de salsa de tomate\",\"Adereza la r\\u00FAcula con aceite, vinagre y sal y acompa\\u00F1a las hamburguesas con una porci\\u00F3n de ensalada\",\"Adorna los platos con unas hojas de perejil\"]"
                        },
                        new
                        {
                            RecetaId = 39,
                            EnlaceVideo = "https://www.cocinatis.com/receta/galletas-de-avena-y-platano-sin-azucar-una-receta-saludable-y-facil-con-solo-3-ingredientes.html",
                            Imagen = "18.jpg",
                            Nombre = "Galletas de Plátano con chocolate"
                        },
                        new
                        {
                            RecetaId = 40,
                            Imagen = "19.jpg",
                            Ingredientes = "[\"Un Pollo Trozeado\",\"Zanahoria\",\"1 pimiento verde\",\"1 pimiento rojo\",\"Vino Blanco\",\"Ketchup\",\"Cebolla\",\"Sal\",\"Aceite de oliva\"]",
                            Nombre = "Pollo a la virulé",
                            Preparacion = "[\"Marcas los trozos de pollo\",\"Picas fina la verdura y la pochas\",\"Cuando est\\u00E9 pochada a\\u00F1ades el pollo\",\"Cuando el pollo est\\u00E9 hecho a\\u00F1ades el vino blanco y el ketchup\"]"
                        });
                });

            modelBuilder.Entity("KintelaDomain.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MenuSemanalReceta", b =>
                {
                    b.Property<int>("MenuSemanalId")
                        .HasColumnType("int");

                    b.Property<int>("RecetasRecetaId")
                        .HasColumnType("int");

                    b.HasKey("MenuSemanalId", "RecetasRecetaId");

                    b.HasIndex("RecetasRecetaId");

                    b.ToTable("MenuSemanalReceta");
                });

            modelBuilder.Entity("CategoriaReceta", b =>
                {
                    b.HasOne("KintelaDomain.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KintelaDomain.Receta", null)
                        .WithMany()
                        .HasForeignKey("RecetasRecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KintelaDomain.Disco", b =>
                {
                    b.HasOne("KintelaDomain.Grupo", "Grupo")
                        .WithMany("Discos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("KintelaDomain.MenuSemanal", b =>
                {
                    b.HasOne("KintelaDomain.Usuario", "Usuario")
                        .WithMany("Menus")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MenuSemanalReceta", b =>
                {
                    b.HasOne("KintelaDomain.MenuSemanal", null)
                        .WithMany()
                        .HasForeignKey("MenuSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KintelaDomain.Receta", null)
                        .WithMany()
                        .HasForeignKey("RecetasRecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KintelaDomain.Grupo", b =>
                {
                    b.Navigation("Discos");
                });

            modelBuilder.Entity("KintelaDomain.Usuario", b =>
                {
                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
